clouder-community/clouder

README.md
doc/cla/individual/michielbdejong.md
doc/cla/sign-cla.md

* third person singular gets -s for  most verbs in English
* adjectives don't get an -s, even when they apply to plural objects
* software is not countable (cannot be used plural). Same for information.
* 'each' goes with singular, not plural
* some word order fixes
* some collocation fixes

Language fixes in readme

---

clouder/clouder_model.py

I just saw there is a second message which has the same text so lets also make that clearer? :+1:

Make a better warning #2

---

clouder_template_postgres/clouder_template_postgres_data.xml
doc/cla/corporate/microcom.md

Installing a specific version of Postgresql to avoid any problem in the future.

postgresql specific version installation

---

clouder_template_postgres/clouder_template_postgres_data.xml
clouder_template_shinken/clouder_template_shinken.py
clouder_template_shinken/clouder_template_shinken_data.xml
doc/cla/corporate/microcom.md

fix shinken img

---

doc/cla/individual/Yenthe666.md

Hi Yannick,
I quickly created one so everything is fine for now and the future, should I ever need to push anything in :)

License agreement

---

clouder/clouder_image.py
clouder/clouder_template_registry/clouder_template_registry_data.xml

implement purging of image from the private registry

---

clouder_template_odoo/clouder_template_odoo_data.xml

re-fix download URL

---

clouder/model.py

Changed for both paramiko's SSHClient and Popen calls in clouder/model.py.

Changed commands execution to allow real time output in logs.

---

clouder_template_odoo/template.xml

Changed odoo_exec template to remove dependency to unofficial python wheel.

Updated odoo_exec template.

---

clouder_template_bind/clouder_template_bind.py
clouder_template_bind/clouder_template_bind_data.xml

I Propose the base of a modification for the BIND template.
What i don't know how to do : making that the user entrie is correct and acceptable by bind (is it an IP address or "none"?) and making the code is sure to make impossible the user to break down the servers.

Making BIND generic

---

clouder_template_postfix/template.py

Added a space at the end of a file to make it PEP-8 complient.
Added conditions to make sure SMTP options are set only when all required
options are filled.

Fixing a bug in clouder_template_postfix

---

clouder_template_bind/template.py

The code tried to access container options on the domain object
That same code also needed to be included in a condition to verify
that the slave_ip option was actually set

Fixed bug with slave_ip option in template_bind

---

clouder_template_magento/__init__.py
clouder_template_magento/__openerp__.py
clouder_template_magento/res/proxy-sslonly.config
clouder_template_magento/res/proxy.config
clouder_template_magento/sources/config.xml
clouder_template_magento/sources/magento.conf
clouder_template_magento/template.py
clouder_template_magento/template.xml

First version tested and working - still a little rough around the edged and could be more automated (there is a command line to launch the magento install instead of using the web wizard).

First version of the magento template plugin for clouder

---

clouder/base.py
clouder/clouder_runner_docker/runner.py
clouder/config.py
clouder/container.py
clouder/model.py
clouder/view.xml
clouder_template_odoo/oneclick.py
clouder_template_odoo/res/proxy-sslonly.config
clouder_template_odoo/res/proxy.config
clouder_template_odoo/template.py
clouder_template_odoo/template.xml
clouder_template_proxy/template.py

Add an intermediate object clouder.job between objects and connector job. Thanks to this, we have the details of all executed command in each objects, even if the action wasn't launched in this object. Also, the actions which are not using the connector now generate log.

Refactoring log

---

doc/getting-started.html

install OCA/Connector and paramiko + erppeek Python libraries

Update and rename getting-started.rst to getting-started.html

---

doc/conf.py

source_suffix = '.rst' -> source_suffix = '.html'

Update conf.py / source_suffix

---

clouder/security/ir.model.access.csv
clouder_asynchronous/__openerp__.py
clouder_asynchronous/security/ir.model.access.csv

Fixes #147, supersedes #150
[FIX] clouder: Remove connector security
[ADD] clouder_asyncronous: Add connector security

[FIX] connector depends

---

clouder/images/backup-bup/Dockerfile
clouder/images/nginx-data/Dockerfile
clouder/images/nginx-exec/Dockerfile
clouder_template_dns/images/bind-data/Dockerfile
clouder_template_dns/images/bind-exec/Dockerfile
clouder_template_mail/images/postfix-data/Dockerfile
clouder_template_mail/images/postfix-exec/Dockerfile
clouder_template_mail/images/spamassassin/Dockerfile
clouder_template_odoo/images/odoo-data/Dockerfile
clouder_template_odoo/images/odoo-exec/Dockerfile
clouder_template_odoo/images/odoo-ssh/Dockerfile
clouder_template_odoo/images/odoo9-files/Dockerfile
clouder_template_postgres/images/postgres-data/Dockerfile

Per https://github.com/clouder-community/clouder/pull/180#discussion_r92349199
* Update Clouder base in all modules

[FIX] Update Clouder Base

---

.travis.yml
clouder/images/base/Dockerfile
clouder/images/base/README.md
clouder/images/base/docker-entrypoint.sh
clouder/images/base/tests/test_command_running
clouder/images/base/tests/test_entrypoint
clouder/tests/__init__.py
clouder/tests/common.py
clouder/tests/test_docker_clouder_base.py

[IMP] clouder: Add Docker travis support

---

.gitignore
doc/getting-started.html

A tiny contribution for this fantastic project!

10.0 doc getting started: add pip dependency + update git ignore
